# Use an official Python runtime as the base image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# RUN pip install --upgrade pip

# Install necessary system dependencies for OpenCV and TensorFlow Lite
# RUN apt-get update && apt-get install -y --no-install-recommends \
#    libgl1 libsm6 libxext6 libxrender-dev
# libglib2.0-0 libsm6 libxext6 libxrender-dev \
#    && apt-get clean \
#    && rm -rf /var/lib/apt/lists/*

# RUN apt-get update && apt-get install -y \
#     libgl1-mesa-glx \
#     libgstreamer1.0-0 \
#     libsm6 \
#     libxext6 \
#     libxrender1 \
#     && rm -rf /var/lib/apt/lists/*

RUN python -m pip install --no-cache-dir --upgrade pip

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt


# Copy the rest of the application code
COPY . .

EXPOSE 5000
CMD ["python", "app.py"]